const rows = [
  {
    id: 1,
    supplier: "Odhiambo",
    category: "Wanjiku",
    completed: 35,
    location: "Nairobi",
    tenure: "2 years",
    rating: 4,
  },
  {
    id: 2,
    supplier: "Kamau",
    category: "Akinyi",
    completed: 42,
    location: "Mombasa",
    tenure: "3 years",
    rating: 5,
  },
  {
    id: 3,
    supplier: "Mutua",
    category: "Achieng",
    completed: 45,
    location: "Kisumu",
    tenure: "1 year",
    rating: 3,
  },
  {
    id: 4,
    supplier: "Gitonga",
    category: "Njeri",
    completed: 16,
    location: "Eldoret",
    tenure: "4 years",
    rating: 2,
  },
  {
    id: 5,
    supplier: "Muthoni",
    category: "Onyango",
    completed: 8,
    location: "Nakuru",
    tenure: "2 years",
    rating: 3,
  },
  {
    id: 6,
    supplier: "Kiptoo",
    category: "Health",
    completed: 150,
    location: "Nairobi",
    tenure: "5 years",
    rating: 4,
  },
  {
    id: 7,
    supplier: "Nyambura",
    category: "Kamande",
    completed: 44,
    location: "Kisii",
    tenure: "2 years",
    rating: 3,
  },
  {
    id: 8,
    supplier: "Ochieng",
    category: "Auma",
    completed: 36,
    location: "Machakos",
    tenure: "3 years",
    rating: 5,
  },
  {
    id: 9,
    supplier: "Kariuki",
    category: "Wambui",
    completed: 65,
    location: "Nairobi",
    tenure: "2 years",
    rating: 4,
  },
];

export { rows };
